symptoms_dict = {
    "Slurred speech": "slurred_speech",
    "Lack of coordination": "incoordination",
    "Unsteady walking": "unsteady_gait",
    "Involuntary eye movements": "nystagmus",
    "Impaired attention": "attention_impairment",
    "Memory problems": "memory_impairment",
    "Reduced consciousness": "stupor",
    "Unconsciousness": "coma",
    "Increased autonomic activity": "autonomic_hyperactivity",
    "Hand tremors": "hand_tremor",
    "Difficulty sleeping": "insomnia",
    "Nausea": "nausea",
    "Vomiting": "vomiting",
    "Visual or auditory hallucinations": "hallucinations",
    "Physical restlessness": "psychomotor_agitation",
    "Anxiety": "anxiety",
    "Seizures": "seizures",
    "Restlessness": "restlessness",
    "Nervousness": "nervousness",
    "Excitement": "excitement",
    "Flushed face": "flushed_face",
    "Increased urination": "diuresis",
    "Digestive disturbances": "gastrointestinal_disturbance",
    "Muscle twitching": "muscle_twitching",
    "Disorganized thoughts": "rambling_thought",
    "Disorganized speech": "rambling_speech",
    "Rapid heartbeat": "tachycardia",
    "Periods of high energy": "periodic_inexhaustibility",
    "Headache": "headache",
    "Fatigue": "fatigue",
    "Drowsiness": "drowsiness",
    "Negative mood": "dysphoric_mood",
    "Depression": "depressed_mood",
    "Difficulty concentrating": "difficulty_concentrating",
    "Muscle pain": "muscle_pain",
    "Muscle stiffness": "muscle_stiffness",
    "Red eyes": "conjunctival_injection",
    "Increased appetite": "increased_appetite",
    "Dry mouth": "dry_mouth",
    "Irritability": "irritability",
    "Anger": "anger",
    "Aggression": "aggression",
    "Weight loss": "weight_loss",
    "High blood pressure": "hypertension",
    "Numbness": "numbness",
    "Pain relief": "analgesia",
    "Poor coordination": "ataxia",
    "Difficulty speaking": "dysarthia",
    "Increased sensitivity to sound": "hyperacusis",
    "Dilated pupils": "pupillary_dilation",
    "Sweating": "sweating",
    "Heart palpitations": "palpitations",
    "Blurred vision": "blurring_vision",
    "Tremors": "tremors",
    "Dizziness": "dizziness",
    "Lethargy": "lethargy",
    "Reduced reflexes": "depressed_reflexes",
    "Slowed physical activity": "psychomotor_retardation",
    "Muscle weakness": "muscle_weakness",
    "Double vision": "diplopia",
    "Euphoria": "euphoria",
    "Frustration": "frustration",
    "Muscle aches": "muscle_aches",
    "Excessive tearing": "lacrimation",
    "Runny nose": "rhinorrhea",
    "Goosebumps": "piloerection",
    "Diarrhea": "diarrhea",
    "Yawning": "yawning",
    "Fever": "fever",
    "Slow heartbeat": "bradycardia",
    "Elevated blood pressure": "elevated_blood_pressure",
    "Lowered blood pressure": "lowered_blood_pressure",
    "Chills": "chills",
    "Respiratory depression": "respiratory_depression",
    "Chest pain": "chest_pain",
    "Irregular heartbeats": "cardiac_arrhythmias",
    "Confusion": "confusion",
    "Abnormal movements": "dyskinesias",
    "Muscle contractions": "dystonias",
    "Excessive sleeping": "hypersomnia",
    "Perspiration": "perspiration"
}
